title = "Mironov Mike"
author = "Mironov Mike"
copyright = "Mironov Mike 2022"
description = "Bitrix24 developer"
profilePicture = "main_photo.jpg"
keywords = "bitrx bitrix24 developer blog"
favicon = "favicons/"
displayMode = "light"
contentratio = "0.8"
disableThemeSwitcher = true
# example ["css/custom.css"]
customCss = ["css/syntax.css", "css/custom_code.css"]
# example ["js/custom.js"]
customJs = []
mainSections = ["blog"]
# images = ["images/site-feature-image.png"]
doNotLoadAnimations = false
# Form Spree Contact Form
#contactFormAction = "https://formspree.io/f/your-form-hash-here"
# Google Fonts
# googleFonts = ["Indie+Flower", "Roboto:ital,wght@0,100;0,400;0,700;1,400"]
# Google Site Verify
#googleSiteVerify = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
singleDateFormat = "02.01.2006"
indexDateFormat = "02.01.2006"
listDateFormat = "02.01.2006"
# Commento Comments
# CommentoURL = "https://commento.example.com/js/commento.js"
# Read More links for truncated summaries
readMore = true
# postSectionName = "blog"
# relatedPosts = true
# numberOfRelatedPosts = 3


reversepagetitle = true # When set to 'true', the Window Title will be reversed to 'Title | Author' instead of the default 'Author | Title'

# hidesidebar = true

[simpleAnalytics]
# enable = true
# customurl = "https://analytics.example.com"

[plausibleAnalytics]
# domain = "example.com"
# serverURL = "https://analytics.example.com"

[umami]
# serverURL = "example.com"
# id = "94db1cb1-74f4-4a40-ad6c-962362670409"

## Math settings
[math]
enable = false  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
use = "katex"  # options: "katex", "mathjax". default is "katex".

## Social links
# use 'fab' when brand icons, use 'fas' when standard solid icons.
[[socialIcons]]
icon = "fa-brands fa-telegram"
title = "Telegram"
url = "https://t.me/mironovmike/"

[[socialIcons]]
icon = "fa-solid fa-at"
title = "E-mail"
url = "mailto:mail@mironovmike.ru"


[[socialIcons]]
icon = "fa-solid fa-link"
title = "Bitrix"
url = "https://dev.1c-bitrix.ru/learning/resume.php?ID=41299847-137941"

[[socialIcons]]
icon = "fa-brands fa-github"
title = "Github"
url = "https://github.com/MironovMike"

